sudo: required
language: generic

services: 
  - docker


before_install:
  - docker build -t ranyshochat/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true ranyshochat/docker-react npm run test -- --coverage
